-- reset.sql
SET REFERENTIAL_INTEGRITY FALSE;

DELETE FROM transactions;
DELETE FROM accounts;
DELETE FROM users;

ALTER TABLE users        ALTER COLUMN id RESTART WITH 1;
ALTER TABLE accounts     ALTER COLUMN id RESTART WITH 1;
ALTER TABLE transactions ALTER COLUMN id RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;